name = "Ne Artemi Silebox Rpg Modpack"
author = "Silebox & ArtCanDy"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d905a8259b986b272ef8fb05444bc23897cd91a1ba0c5446430fa37a65ccdb57"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
