name: Build Modpack
on: [push] # Собирать при каждом пуше

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Скачиваем ваш репозиторий

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21'

      - name: Install packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Export to .zip (CurseForge/Manual)
        run: packwiz curseforge export --side client -o modpack.zip
        
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Latest Build"
          files: modpack.zip
          body: "Автоматическая сборка модпака. Обновлено: ${{ github.event.head_commit.timestamp }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}